version: '3.6'

services:
  sqlserver:
    restart: on-failure
    image: microsoft/mssql-server-linux:2017-CU9-GDR2
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
    volumes:
     - ./volumes/mssql6:/var/opt/mssql/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    restart: on-failure
    ports:
      - 5601:5601
    environment:
      - xpack.security.enabled=false
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    restart: on-failure
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data

  zookeeper:
    image: debezium/zookeeper:0.10
    restart: on-failure
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    volumes:
      - ./volumes/zookeeper/data:/zookeeper/data
      - ./volumes/zookeeper/txns:/zookeeper/txns

  kafka:
    image: debezium/kafka:0.10
    restart: on-failure
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - ./volumes/kafka/data:/kafka/data
      - ./volumes/kafka/logs:/kafka/logs

  connect:
    image: debezium/connect-jdbc-es:0.10
    build:
      context: ./debezium-jdbc-es
    restart: on-failure
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - sqlserver
      - elasticsearch
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      
networks:
  default:
    external:
      name: webproxy